name: Build Packages Install Packages on AzFunc

on:
  push:
    branches: [ juzuluag/enh_ci_for_lib ]
  pull_request:
    branches: [ juzuluag/enh_ci_for_lib ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

env:
  DOTNET_SRC_DIR: "./src"
  PREFIX: "0.0.9"
  DOTNET_SOLUTION: "./src/CarbonAwareSDK.sln"
  OUTPUT_DIR: "packages"

jobs:
  dotnet-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Make package dir
        run: mkdir -p ${{ env.OUTPUT_DIR }}
      - name: Pack
        run: |
          dotnet pack ${{ env.DOTNET_SOLUTION }} -o ${{ env.OUTPUT_DIR }} -c Release \
            -p:VersionPrefix=${{ env.PREFIX }} \
            -p:VersionSuffix=beta \
            -p:Authors="Microsoft" \
            -p:Company="Microsoft" \
            -p:Title="Green Software Foundation SDK" \
            -p:PackageTags="Green-Software-Foundation GSF Microsoft" \
            -p:SourceRevisionId=c20572dccb64b3bd7e585ddbef8a4c68255d0dd8 \
            -p:RepositoryUrl="https://github.com/microsoft/carbon-aware-sdk" \
            -p:RepositoryType=git \
            -p:RepositoryBranch=dev \
            -p:Description="Green Software Foundation SDK. Allows to get Carbon Emissions information from WattTime and ElectricityMap sources." \
            -p:PackageLicenseExpression=MIT
      - name: Create demo Console App
        run: dotnet new console -n DemoApp
      - name: Add Packages
        run: dotnet add DemoApp/DemoApp.csproj package GSF.CarbonIntensity -s ${{ env.OUTPUT_DIR }} --prerelease
      - name: Build demo app
        run: dotnet build DemoApp/DemoApp.csproj


