name: Build Packages Install Packages on ConsoleAppSample

on:
  push:
    branches: [ juzuluag/enh_ci_for_lib ]
  pull_request:
    branches: [ juzuluag/enh_ci_for_lib ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

env:
  PREFIX: "0.0.9"
  DOTNET_SOLUTION: "./src/CarbonAwareSDK.sln"
  OUTPUT_DIR: "packages"
  CONSOLE_APP: "./ms-internal/lib-integration/samples/ConsoleAppSample/ConsoleAppSample.csproj"

jobs:
  dotnet-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Make package dir
        run: mkdir -p ${{ env.OUTPUT_DIR }}
      - name: Pack
        run: |
          dotnet pack ${{ env.DOTNET_SOLUTION }} -o ${{ env.OUTPUT_DIR }} -c Release \
            -p:VersionPrefix=${{ env.PREFIX }} \
            -p:VersionSuffix=beta \
            -p:Authors="Microsoft" \
            -p:Company="Microsoft" \
            -p:Title="Green Software Foundation SDK" \
            -p:PackageTags="Green-Software-Foundation GSF Microsoft" \
            -p:SourceRevisionId=c20572dccb64b3bd7e585ddbef8a4c68255d0dd8 \
            -p:RepositoryUrl="https://github.com/microsoft/carbon-aware-sdk" \
            -p:RepositoryType=git \
            -p:RepositoryBranch=dev \
            -p:Description="Green Software Foundation SDK. Allows to get Carbon Emissions information from WattTime and ElectricityMap sources." \
            -p:PackageLicenseExpression=MIT

      - name: Restore current packages for ConsoleAppSample
        run: dotnet restore ${{ env.CONSOLE_APP }}

      - name: Add packages to ConsoleAppSample
        run: |
          declare -a packages=(
            "GSF.CarbonIntensity"
          )
          for pname in "${packages[@]}"
          do
            dotnet add ${{ env.CONSOLE_APP }} package $pname -s  ${{ env.OUTPUT_DIR }} --prerelease
          done

      - name: Restore packages after Add to ConsoleAppSample
        run: dotnet restore ${{ env.CONSOLE_APP }}

      - name: Build ConsoleAppSample
        run: dotnet build ${{ env.CONSOLE_APP }}

      - name: Run ConsoleAppSample
        run: dotnet run --project ${{ env.CONSOLE_APP }}
